### PR TITLE
Implement role-based access control (fixes #15, fixes #95)

### LINKED ISSUE #15: Group-based user permissions
Possibility to assign users to groups and to assign permissions to groups. First feature to be implemented: ability to read private records.

### LINKED ISSUE #95: Hide all private records on per-request basis
This is one of the most important missing features in my opinion: we need to add the possibility to only return non-private information on all endpoints. This can later (= soon) be enabled/disabled on a per-user basis depending on permissions (#15) but for now we can just treat it as a global option, too.

In my old backend, I solved this by simply [returning a `PrivateProxyDb`](https://github.com/DavidMStraub/gramps-webapp/blob/master/gramps_webapp/db.py#L52-L56) instead of the actual database in each request (this would be `get_dbstate` in our case). That's clean and very easy to implement. However, since the proxy DB only overloads a subset of the underlying DB's mathods ([see source](https://github.com/gramps-project/gramps/blob/master/gramps/gen/proxy/private.py)), I suspect we are currently using other, low-level, methods which return private data even when used on the `PrivateProxyDb`. So we need to carefully check all our code for such cases, find ways to make it safe, and add tests to make sure we don't leak private info.

Please feel free to use this thread to post any observations/checks you have made.

### PR DESCRIPTION
**Pull request by DavidMStraub**
This cannot be merged before #99 but is otherwise finished.

Some details on the implementation:

- The user database only stores a single integer, the user role. This was in fact already the case before.
- constants in `auth.const` map these integers to roles, e.g. `ROLE_OWNER`
- a constant dict in the same module assigns permissions, that are string constants, to roles. E.g., `PERM_VIEW_PRIVATE` is the permission to view private records
- The permissions are stored in the JWT, i.e. in case they are changed, the change is effective at the latest after 15 minutes (when the token needs to be refreshed)
- The JWT does not know anything about user roles, these are managed by the backend
- The database does not know anything about permissions, these are managed by the backend

The nice thing about this setup is that we can have a fine-grained permissions system but do not need to query the user DB for every request.

So far, I have only implemented the filtering of private records using `PrivateProxyDb` (#95), but the function `require_permissions(scope)` can be used anywhere in any method to raise a 403 if permission for a given action is not present.

### CODE REVIEW

**Comment by DavidMStraub** [comment]
Yay, PR/issue no. :100: :tada:

**Review by cdhorn — APPROVED** [review]
This is very nice!

**Comment by DavidMStraub** [comment]
Done I think. I had to make a slightly ugly patch in e1b69ad to make the metadata endpoint work in case a `PrivateProxyDb` is used (#95), because some of the methods are not defined for the proxy.

**Comment by Nick-Hall** [comment]
Yes.  It would be neater to add these methods to the [`ProxyDbBase`](https://github.com/gramps-project/gramps/blob/master/gramps/gen/proxy/proxybase.py#L81) class.

**Comment by DavidMStraub** [comment]
I can submit a PR. Once this has landed in Gramps, we can remove the patch again.

**Comment by DavidMStraub** [comment]
I would merge this in a couple of hours if there are no objections (we can always improve on it).

**Comment by cdhorn** [comment]
Certainly none here, nice work!

**Pull request merged**
