### PR TITLE
Add more person attributes

### PR DESCRIPTION
**Pull request by cdhorn**
@DavidMStraub This is reswizzled to factor out gramps id and use handle and with just changes to the person endpoint.

### CODE REVIEW

**Comment by cdhorn** [comment]
Silly me, initial commit didn't actually accept handle for the individual lookup because I just kept naturally using gramps id. It works now, and if the handle lookup fails it falls back and tries to treat it like a Gramps id before throwing a 404 which is convenient for the test suite since the handle will always be changing.

**Comment by DavidMStraub** [comment]
Thanks!

Concerning overloading the handle with the Gramps ID, I am a bit unhappy about it as it seems like a hack to me. For an API endpoint like `/api/person/something`, I would expect the `something` to be one kind of object only. Since we decided to use the handle for that, I would really just use that.

If someone wants to look up an object by something else, be it the Gramps ID, the persons name, ..., they can use #17 as mentioned in https://github.com/gramps-project/web-api/pull/4#issuecomment-702915896.

Hope you are OK with this.

**Comment by cdhorn** [comment]
Flask jsonify sorts keys by default, do we want to preserve that behaviour?

**Comment by DavidMStraub** [comment]
Interesting question, I wasn't aware of it. I would tend to say yes, especially that we aim at supporting Python 3.5 (since Gramps 5.2 will support it) and dictionaries don't remember their order until 3.6. So if `jsonify` *doesn't* sort, the order will depend on the Python version.

**Comment by cdhorn** [comment]
Okay I'll shuffle stuff around to account for it.

**Comment by DavidMStraub** [comment]
Why do you actually want to sort the output of `object_to_dict`? That doesn't have any effect, does it?

**Comment by DavidMStraub** [comment]
Do you know why the "files changed" tab shows all the changes from my merged PR #19 as well? Can you please try rebasing on `master`?

**Comment by cdhorn** [comment]
Shouldn't that just be less work for Flask jsonify later?

**Comment by cdhorn** [comment]
Also sorry if I should do things differently, I'm a little new to this... please be patient with me.

**Comment by DavidMStraub** [comment]
> Also sorry if I should do things differently, I'm a little new to this... please be patient with me.

No worries!

> Shouldn't that just be less work for Flask jsonify later?

The sorting is done by Python's `json` standard library, is implemented in C and is very fast (I just checked). So it's going to be faster than everything else done by this function.

Don't get me wrong, it doesn't hurt either, but I would say it's just a case of "premature optimization" :wink:

**Comment by cdhorn** [comment]
@DavidMStraub can you take a look over the simplify branch in my forked repo, I think it is more like what @Nick-Hall had been suggesting and may be a better approach. One major change is having a static format, it may send more over the wire but the client doesn't need to worry about testing if a key is present all the time before referencing something. Not sure if you are in agreement with that though.

**Comment by DavidMStraub** [comment]
I had a brief look. Great job, and I agree that it's much more elegant to leverage everything that is already there like `citation_list`, `note_list`, `tag_list` etc.

Concerning the "static format", I'm not so sure, I would rather keep the response limited to non-empty keys ([some discussion here](https://softwareengineering.stackexchange.com/questions/285010/null-vs-missing-key-in-rest-api-response)), but I don't think we have to decide it right now. It will be trivial to filter out empty ones later if we decide to do so.

The only thing I'm not sure about is how to deal with the "denormalized" keys. As you wrote before, using only the "raw" format will leave the "apps" to do all the work (assembling back the name from its pieces, finding the birth event and its date, formatting it ...) so we *do* want to have this "preprocessed" information. But simply adding additional keys next to the "raw data" also seems strange to me.

But I agree that your new branch is a much cleaner interpretation, so I suggest to continue with a PR of this branch and we can discuss the details there.

BTW, are you using `pre-commit` as described in the readme? The code looks like it's not formatted with `black`.

**Comment by DavidMStraub** [comment]
>  But simply adding additional keys next to the "raw data" also seems strange to me.

I thought a bit more about this and one possibility would be to have
 
- `/api/person/some-handle` return the raw dictionary
- `/api/person/some-handle?format=simple` (or something similar) return something that is closer to what I had in the web app backend, so derived quantities like `{'birthdate': ..., 'birthplace': ..., 'name_given': ...}`

The reason I think this is useful is because the second, shorter format would be useful to display lists of objects (such as [this](https://mysterious-cove-02458.herokuapp.com/people) - username and password = `test`) without having to iterate through nested sub-properties, while the raw format (with optional `recursion`) could be used to show object details.

In any case, I think it's useful if, for the moment, we just implement the raw format based on your new branch and then add more stuff later.

**Comment by cdhorn** [comment]
I have obligations today so will get to this later in the day.

Sorry I think I overlooked the pre-commit hooks, will setup. 

For any denormalized attributes, and I agree they are a good idea, why not group them together under a single "profile" attribute?  Then in addition to a strip option we can have a raw option that strips the profile out and a keywords option to take a comma delimited set of keys to return? Aka profile,handle,gramps_id?  I think that would work well.

**Comment by DavidMStraub** [comment]
> For any denormalized attributes, and I agree they are a good idea, why not group them together under a single "profile" attribute? Then in addition to a strip option we can have a raw option that strips the profile out and a keywords option to take a comma delimited set of keys to return? Aka profile,handle,gramps_id? I think that would work well.

Yes, sound good!

**Comment by Nick-Hall** [comment]
This seems to be heading in the right direction.

Do we want to include fallbacks for the birth and death events?  Perhaps these events should be structures:
```python
[{
  'type': 'Baptism',
  'date': '1900-1-1',
  'place': 'London, England'
},
{
  'type': 'Death',
  'date': '1950-2-2',
  'place': 'London, England'
}]
```
Which leads to the question:  How do we want to represent a `GrampsType`?  Should we provide a translation based on the browser locale?  e.g. `[15, 'Baptism', 'Baptême']` in French.

How should we handle the `group_as` and `sort_as` fields of a name?  Do they need to form part of the name or will all grouping and sorting be done on the server?

**Comment by DavidMStraub** [comment]
> Perhaps these events should be structures:

In the "raw" format that attempts to be close to the serialized JSON, I think it would be, for a person,

```
{"_class": "Person", ...,  "event_ref_list": [
    {"_class": "EventRef", ..., "ref": "Z8BBWT1N2B53UH0LHP", ...}
], ...}
```
while @cdhorn was suggesting to have in addition a `recursion` option, that would replace the handle by the serialized event,

```
{"_class": "Person", ...,  "event_ref_list": [
    {"_class": "EventRef", ..., "ref": {
            {"_class": "Event", ..., "type": {"_class": "EventType", "string": "Birth"}}
}
        }
    ...}
], ...}
```

Your suggestion would be closer to the "simple" format discussed above, and I see motivation for both formats.

Concerning

> Which leads to the question: How do we want to represent a GrampsType? Should we provide a translation based on the browser locale? e.g. [15, 'Baptism', 'Baptême'] in French.

I would simply introduce a keyword argument `lang=de_DE` etc., since this would allow the user to change the language in an app (see e.g. [this feature request](https://github.com/DavidMStraub/gramps-webapp/issues/31)). Using the browser locale would be an app implementation detail (i.e. setting `lang` in API calls according to the locale). The API doesn't even have to be called from a browser...

BTW, how does `to_json` deal with this? I guess it simply uses the current `GRAMPSLOCALE`?

**Comment by DavidMStraub** [comment]
BTW, maybe we should open separate issues for all these different topics :slightly_smiling_face:

**Comment by Nick-Hall** [comment]
> Your suggestion would be closer to the "simple" format discussed above, and I see motivation for both formats.

It was a suggestion for the contents of the "profile" attribute, rather than using `birthdate`, `birthplace`, `deathdate` and `deathplace`.

**Comment by Nick-Hall** [comment]
> BTW, how does to_json deal with this?

It doesn't need to it just uses the English string for pre-defined values and the string provided for custom values.  This is enough information for `from_json` to reconstruct the object.

**Comment by DavidMStraub** [comment]
>  It was a suggestion for the contents of the "profile" attribute, rather than using birthdate, birthplace, deathdate and deathplace.

Oh, now I get it. Yes, good idea.

> It doesn't need to it just uses the English string for pre-defined values and the string provided for custom values. This is enough information for from_json to reconstruct the object.

OK, I was just surprised that the event role ("Primary"/"Primär") and event names ("Birth"/"Geburt") are localized (German) when I call `to_json`. For the "raw" API endpoint, I guess we also have to allow changing this.

**Pull request closed without merging**
